/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.rtmigo.libr

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        assertTrue(TheClass().x2(3)==6)
    }
}
