/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.5.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.6.21"

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    id("maven-publish")
}

publishing {
    publications {
        create<MavenPublication>("earth") {
            from(components["java"])
            pom {
                developers {
                    developer {
                        name.set("Artsiom iG")
                        email.set("ortemeo@gmail.com")
                        //name.set("Slartibartfast")
                        //email.set("slartibartfast@magrathea.net")
                    }
                }
                val repo = "precise_kt"
                //val user "rtmigo"
                scm {
                    connection.set("scm:git:git://github.com/rtmigo/$repo.git")
                    url.set("https://github.com/rtmigo/$repo")
                }
                licenses {
                    license {
                        name.set("MIT")
                        url.set("https://github.com/rtmigo/$repo/blob/HEAD/LICENSE")
                    }
                }
            }
        }
    }
}

group = "io.github.rtmigo"
version = "1.2.3-rc2"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    //implementation("com.google.guava:guava:31.0.1-jre")

    // Use the Kotlin test library.
    //testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    //testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    //api("org.apache.commons:commons-math3:3.6.1")
}
