name: ci

on:
  push:
    branches: [ dev ]
    paths-ignore:
      - '**.md'
      - '**.txt'

concurrency:
  # subsequently queued workflow run will interrupt previous runs
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:

  unit-test:
    #needs: [smoketest]
    timeout-minutes: 10

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [
          ubuntu-latest,
          # macos-latest
        ]
        jdk-version: [
          8,
          18
        ]
        gradle-version: [
          '7.5.1',
          # '7.0.1',
        ]


    #    strategy:
    #      matrix:
    #        os: [ ubuntu-latest ]
    #        jdk-version: [ 8 ]
    #        gradle-version: [ '7.5.1' ]
    #        python-version: [ '3.10' ]
    #        isFull:
    #          - ${{ contains(github.event.head_commit.message, '!!full') }}
    #        include:
    #          - isFull: true
    #            os: macos-latest
    #          - isFull: true
    #            python-version: '3.11.0-rc.2'
    #          - isFull: true
    #            jdk-version: 18
    #          - isFull: true
    #            gradle-version: '7.0.1'

    steps:
      - uses: actions/checkout@master
      - name: Setup JDK
        uses: actions/setup-java@master
        with:
          java-version: ${{ matrix.jdk-version }}
          distribution: 'temurin'
          cache: gradle
      - name: Unit tests
        run: |
          #export GPG_TTY=$(tty)
          ./gradlew build
          #python hap.py test ${{ matrix.gradle-version }}
        env:
          MAVEN_GPG_KEY: ${{ secrets.MAVEN_GPG_KEY }}
          MAVEN_GPG_PASSWORD: ${{ secrets.MAVEN_GPG_PASSWORD }}
          #SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          #SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

  python-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: '3.10'
      - name: Setup JDK
        uses: actions/setup-java@master
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle
      - name: Build uber jar
        run: ./gradlew uberJar
      - name: Run tests
        run: python src/test/python/test_uber.py        

  to-staging:
    needs: [unit-test, python-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge current -> staging
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: staging
          github_token: ${{ github.token }}


  release-flag:
    if: contains(github.event.head_commit.message, '!!release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master



  gh-release:
    needs: [release-flag, to-staging]
    timeout-minutes: 10

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Setup JDK
        uses: actions/setup-java@master
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle
      - name: Get the project version
        id: get_version
        run: |
          git fetch --all --tags
          VERSION=$(./gradlew properties | grep version | awk '{print $2}')
          echo "Version $VERSION"
          
          [[ ! $A =~ .*SNAPSHOT.* ]] # check it's not a snapshot version
          [[ -z $(git tag -l $VERSION) ]] # check this version was not published  
          
          echo "result=$VERSION" >>$GITHUB_OUTPUT
      - name: Build
        run: |
          #export GPG_TTY=$(tty)
          ./gradlew uberJar
          mv ./build/libs/mavence.uber.jar ./build/libs/mavence.jar
        env:
          MAVEN_GPG_KEY: ${{ secrets.MAVEN_GPG_KEY }}
          MAVEN_GPG_PASSWORD: ${{ secrets.MAVEN_GPG_PASSWORD }}
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.result }}
          files: ./build/libs/mavence.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
